---
refresh_interval: 2 # seconds
max_price: 650 # dollars/euros/etc
urls:
  - https://amzn.to/2IVECfY
  - https://amzn.to/2IUzhpa
  - https://amzn.to/37ldNuO
  - https://amzn.to/3nm2fxf
  - https://amzn.to/2Kn4At3
  - https://amzn.to/34h9TRY
  - https://amzn.to/3r00Ka8
  - https://amzn.to/3adnZaF
  - https://amzn.to/3oZHg3H
  - https://amzn.to/2KqlMOk
  - https://amzn.to/385ydHE
  - https://amzn.to/3aaRs5f
  - https://amzn.to/37jLRYf
  - https://amzn.to/3nnYQOq
  - https://amzn.to/2LAN6tL
  - https://amzn.to/3qYXVGj
  - https://amzn.to/3r2slr0
...
