---
refresh_interval: 2 # seconds
max_price: 650 # dollars/euros/etc
urls:
  - https://www.amazon.com/dp/B08L8HPKR6
  - https://www.amazon.com/dp/B08L8LG4M3
  - https://www.amazon.com/dp/B08L8JNTXQ
  - https://www.amazon.com/dp/B08L8KC1J7
  - https://www.amazon.com/dp/B08L8L9TCZ
  - https://www.amazon.com/dp/B08LW46GH2
  - https://www.amazon.com/dp/B08L8L71SM
  - https://www.amazon.com/dp/B08KY322TH
  - https://www.amazon.com/dp/B08KXZV626
  - https://www.amazon.com/dp/B08KY266MG
  - https://www.amazon.com/dp/B08KWN2LZG
  - https://www.amazon.com/dp/B08KWPDXJZ
  - https://www.amazon.com/dp/B08KWLMZV4
  - https://www.amazon.com/dp/B08HBF5L3K
  - https://www.amazon.com/dp/B08HBJB7YD
  - https://www.amazon.com/dp/B08LF32LJ6
  - https://www.amazon.com/dp/B08LF1CWT2
  -https://www.amazon.com/OLOy-288-Pin-Desktop-Gaming-MD4U083016BJDA/dp/B083NPX9TJ/ref=sr_1_1_sspa?dchild=1&keywords=ram&qid=1607808492&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFWVTJGRkdHOTFOTUkmZW5jcnlwdGVkSWQ9QTAxMDYxNjgzTVdWR1VERzRLOTlLJmVuY3J5cHRlZEFkSWQ9QTA3MzYxMTVDQ0dJVkhZRUJBVkUmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl
...
