---
max_price: 400 # dollars/euros/etc
refresh_interval: 2 # seconds
urls:
  - https://www.newegg.com/amd-ryzen-5-5600x/p/N82E16819113666?Item=N82E16819113666&Tpk=19-113-666
  - https://amzn.to/3oT1UlV
...